apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: my-nodedb-app
spec:
  # 2 Pods should exist at all times.
  replicas: 1
  selector:
    matchLabels:
      app: nodedb-app
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: nodedb-app
    spec:
      containers:
        - name: mongo-db
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
        - name: nodedb-app
          # Run this image
          image: bibekk477/node-mongo-db:06
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
      volumes:
        - name: mongo-storage
          emptyDir: {}

---
kind: Service
apiVersion: v1
metadata:
  # Unique key of the Service instance
  name: service-my-nodedb-app
spec:
  ports:
    # Accept traffic sent to port 80
    - name: http
      port: 8080
      targetPort: 3000
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    app: nodedb-app # send traffic to pods with label app=nodedb-app
  # Create an HA proxy in the cloud provider
  # with an External IP address - *Only supported
  # by some cloud providers*
  type: LoadBalancer
